CREATE TABLE "GCG_4231_TRUEVIEW"(
 "DEPARTMENT" CHAR(4),
 "WORKCENTER" CHAR(4),
 "JOBSUFFIX" CHAR(10),
 "PART" CHAR(20),
 "SEQ" CHAR(6),
 "DESCRIPTION" CHAR(30),
 "EST_RATE" DOUBLE,
 "ACT_RATE" DOUBLE,
 "CURRENT_TIME" DOUBLE,
 "CURRENT_DATE" DATE,
 "AVG_RATE" DOUBLE);
